(let ((file-name-handler-alist nil)
      (gc-cons-threshold 100000000))
  (add-to-list 'load-path "~/.emacs.d/config")
  (add-to-list 'load-path "~/.emacs.d/tempo")
  (require 'attic-options)
  (require 'attic-functions)
  (require 'attic-packages)
  (require 'attic-keys)
  (when (file-exists-p "~/.system.el")
    (load-file "~/.system.el")))
