(let ((file-name-handler-alist nil)
      (gc-cons-threshold 100000000))
  (unless (file-exists-p "~/.emacs.d/multiple-cursors.el/multiple-cursors.el")
    (shell-command "cd ~/.emacs.d && git submodule init && git submodule update"))
  (add-to-list 'load-path "~/.emacs.d/multiple-cursors.el")
  (add-to-list 'load-path "~/.emacs.d/config")
  (add-to-list 'load-path "~/.emacs.d/tempo")
  (add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e")
  (require 'multiple-cursors)
  (require 'attic-options)
  (require 'attic-functions)
  (require 'attic-packages)
  (require 'attic-keys)
  (require 'attic-colors)
  (when (file-exists-p "~/.system.el")
    (load-file "~/.system.el"))

  ;; temp hack
  (bind-key "<return>" 'newline mc/keymap)
  (bind-key* "M-K" 'mc/mark-previous-like-this)
  (bind-key* "M-J" 'mc/mark-next-like-this)
  (multiple-cursors-mode t))
