(tool-bar-mode 0)
(menu-bar-mode 0)
(scroll-bar-mode 0)
(auto-complete-mode 1)
(multiple-cursors-mode 1)
(workgroups-mode 1)
(show-paren-mode t)
(window-numbering-mode 1)
(yas-global-mode 1)
(god-mode)
(global-rainbow-delimiters-mode)

(provide 'my-modes)
