(require 'auto-complete-config)
(require 'god-mode)
(require 'helm)
(require 'helm-ls-git)
(require 'helm-swoop)
(require 'multiple-cursors)
(require 'redo+)
(require 'magit)
(require 'fbterm)
(require 'rebar)
(require 'distel)
(require 'flymake)
(require 'tempo)
(require 'web-mode)
(require 'indent-of-doom)

;; Modes
(global-linum-mode t)
(global-rainbow-delimiters-mode)
(god-mode)
(key-chord-mode 1)
(multiple-cursors-mode 1)
(show-paren-mode t)
(window-numbering-mode 1)
(wrap-region-global-mode t)
(yas-global-mode 1)
(smartparens-global-mode t)

(provide 'my-modes)
