#!/bin/bash

echo 'group :development do
  gem "guard-elixir"
end' > Gemfile

echo 'notification :emacs
guard :elixir do
  watch(%r{^test/(.*)_test\.exs})
  watch(%r{^lib/(.+)\.ex$})           { |m| "test/#{m[1]}_test.exs" }
  watch(%r{^test/test_helper.exs$})   { "test" }
end' > Guardfile
