#!/bin/bash

while [ $PWD != "/" ]; do
    if [ -f Makefile ]; then
        make $1
        exit 0
    fi
    cd ..
done


# case "$1" in
# 1)  while [ $PWD != "/" ]; do
#         if [ -f Makefile ]; then
#             make
#             exit 0
#         fi
#         cd ..
#     done
#     ;;
# 2)  echo "foo"
#     ;;
# 3)  while [ $PWD != "/" ]; do
#         if [ -f Makefile ]; then
#             make start
#             exit 0
#         fi
#         cd ..
#     done
#     ;;
# 4)  while [ $PWD != "/" ]; do
#         if [ -f Makefile ]; then
#             make restart
#             exit 0
#         fi
#         cd ..
#     done
#     ;;
# esac
